const products = [
  {
    id: 1,
    title: "Shade Color Design Eyeglass",
    image: "/images/sun1.png",
    price: 200,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/kids.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 2,
    title: "High End Design Classic Frame",
    image: "/images/sun1.png",
    price: 300,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳700" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 3,
    title: "High End Design Eyeglass",
    image: "/images/sun1.png",
    price: 400,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 4,
    title: "High End Quality Rim less Eyeware",
    image: "/images/sun1.png",
    price: 500,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 5,
    title: "High End Quality Rim less Frame",
    image: "/images/sun1.png",
    price: 600,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 6,
    title: "High End Quality Rim less Eyeglass",
    image: "/images/sun1.png",
    price: 700,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 7,
    title: "Shade Color Design Eyeglass 7",
    image: "/images/sun1.png",
    price: 200,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/kids.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 8,
    title: "High End Design Classic Frame 8",
    image: "/images/sun1.png",
    price: 300,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳700" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 9,
    title: "High End Design Eyeglass 9",
    image: "/images/sun1.png",
    price: 400,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 10,
    title: "High End Quality Rim less Eyeware 10",
    image: "/images/sun1.png",
    price: 500,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
      { image: "/images/sun1.png" },
    ],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 11,
    title: "High End Quality Rim less Frame 11",
    image: "/images/sun1.png",
    price: 600,
    ability: "In stock",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 12,
    title: "High End Quality Rim less Eyeglass 12",
    image: "/images/sun1.png",
    price: 700,
    ability: "Stock Out",
    Sku: "DKE04461",
    sizeGuide: "Delivery & Return",
    detailsImage: [],
    details: {
      modelNumber: "DKE04461",
      size: "54-16-141 mm",
      frameMaterial: "High quality Metal & Fiber",
      frameLensMaterial: "Polycarbonate",
      frameAttribution: "High Quality, Flexible & Durable",
      usage: "Eyeglasses Frame or Prescription Optical Frame",
      lensFunction:
        "UV400, Anti Reflection,Anti Blue Ray & more functions depending on Lens types.",
    },
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
];

export default products;
