const products = [
  {
    id: 1,
    title: "Shade Color Design Eyeglass",
    image: "/images/sun1.png",
    price: 200,
    ability: "In stock",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 2,
    title: "High End Design Classic Frame",
    image: "/images/sun1.png",
    price: 300,
    ability: "Stock Out",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 3,
    title: "High End Design Eyeglass",
    image: "/images/sun1.png",
    price: 400,
    ability: "In stock",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 4,
    title: "High End Quality Rim less Eyeware",
    image: "/images/sun1.png",
    price: 500,
    ability: "Stock Out",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 5,
    title: "High End Quality Rim less Frame",
    image: "/images/sun1.png",
    price: 600,
    ability: "In stock",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
  {
    id: 6,
    title: "High End Quality Rim less Eyeglass",
    image: "/images/sun1.png",
    price: 700,
    ability: "Stock Out",
    Sku: "DKE04461",
    listType: [
      { list: "Frame Only" },
      { list: "Basic Lens + ৳200" },
      { list: "Standard Lens + ৳300" },
      { list: "Premium Standard Lens + ৳500" },
      { list: "Blue Light Block Glass + ৳500" },
    ],
  },
];

export default products;
